# -*- coding: utf-8 -*-
"""Forecasting BMKG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14LX0wroF_pZdbWIWPfPPQl6YE4Ro85mX

#Import Library
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import mean_absolute_error, mean_squared_error

"""#Read Data"""

df = pd.read_excel("https://raw.github.com/dewitrilestari/Portofolio/main/Forecasting/Merge%20Data/Juli%202024%20-%20Juli%202026.xlsx")

df

"""#Data Checking

##Data Type
"""

df.info()

"""##Statistic"""

df.describe()

"""##Missing Value"""

df.isnull().sum()

"""##Duplicate"""

df.duplicated().sum()

"""##Feature Selection"""

if 'RR' in df.columns:
    df['RR'] = df['RR'].clip(lower=0)
df_numeric = df.drop(columns=['Tanggal', 'DDD_CAR'], errors='ignore')
matriks_korelasi = df_numeric.corr()

plt.figure(figsize=(6, 5))
sns.heatmap(matriks_korelasi, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, vmin=-1, vmax=1)

plt.title('Heatmap Korelasi Antar Parameter Cuaca BMKG', fontsize=14, pad=20)
plt.show()

"""#EDA

##Time Series
"""

df['Tanggal'] = pd.to_datetime(df['Tanggal'])

monthly_rr = df.groupby(pd.Grouper(key='Tanggal', freq='MS'))['RR'].sum()

plt.figure(figsize=(10, 2))
plt.plot(monthly_rr)
plt.title('Monthly Curah Hujan (RR)')
plt.show()

"""**Pola Musiman**
* Periode Musim Kemarau (Juli - September): Ditunjukkan oleh lembah grafik yang sangat rendah, mendekati $0$ mm. Ini terlihat jelas pada periode Juli - Oktober 2024, Juni - September 2025, dan kembali turun drastis di Mei - Juli 2026. Pada bulan-bulan ini, akumulasi hujan hampir tidak ada.
* Periode Musim Hujan (Oktober - Mei): Ditunjukkan oleh grafik yang naik drastis. Peningkatan curah hujan mulai terjadi sekitar bulan Oktober dan mencapai puncaknya di sekitar bulan Januari hingga April.

**Perbandingan Antar Tahun**
* Siklus 2024–2025: Curah hujan mulai meningkat di akhir 2024, sempat turun sedikit di awal 2025 (sekitar Februari), lalu melonjak ke puncak tertingginya di sekitar Maret 2025 dengan total curah hujan bulanan menembus $600$ mm.
* Siklus 2025–2026: Memiliki pola yang mirip, di mana hujan mulai naik di akhir 2025 dan mencapai puncak tertingginya di sekitar Januari 2026 dengan akumulasi mencapai hampir $600$ mm, sebelum akhirnya turun kembali menuju musim kemarau di pertengahan 2026.

##Data Distribution
"""

kolom_numerik = df.select_dtypes(include=['float64', 'float32', 'int64', 'int32']).columns
ringkasan_outliers = {}

for col in kolom_numerik:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    batas_bawah = Q1 - 1.5 * IQR
    batas_atas = Q3 + 1.5 * IQR

    kondisi_outlier = (df[col] < batas_bawah) | (df[col] > batas_atas)
    jumlah_outliers = df[kondisi_outlier].shape[0]
    persentase = (jumlah_outliers / len(df)) * 100

    ringkasan_outliers[col] = [jumlah_outliers, f"{persentase:.2f}%"]

jumlah_kolom = len(kolom_numerik)
fig, axes = plt.subplots(nrows=(jumlah_kolom + 2) // 3, ncols=3, figsize=(16, 4 * ((jumlah_kolom + 2) // 3)))
axes = axes.flatten()

for i, col in enumerate(kolom_numerik):
    sns.boxplot(y=df[col], ax=axes[i], color='skyblue')
    axes[i].set_title(f'Boxplot {col}', fontsize=12)
    axes[i].set_ylabel('')
    axes[i].grid(True, linestyle='--', alpha=0.6)

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""##Rolling Mean and Rolling Standard Deviation"""

# Menghitung Rolling Mean & Rolling Std dengan jendela (window) 3 bulan
rolling_window = 3
rolling_mean = monthly_rr.rolling(window=rolling_window).mean()
rolling_std = monthly_rr.rolling(window=rolling_window).std()

# Visualisasi
plt.figure(figsize=(9, 4))
plt.plot(monthly_rr, label='Data Aktual (Monthly RR)', color='blue', alpha=0.4)
plt.plot(rolling_mean, label=f'Rolling Mean ({rolling_window}-Month)', color='red', linewidth=2)
plt.plot(rolling_std, label=f'Rolling Std ({rolling_window}-Month)', color='black', linestyle='--')

plt.title('Analisis Rolling Mean & Rolling Standard Deviation')
plt.xlabel('Tanggal')
plt.ylabel('Curah Hujan (mm)')
plt.legend()
plt.grid(True)
plt.show()

"""**Rolling Mean**
* Pola Siklus Tahunan: Terlihat jelas ada dua gelombang puncak utama di grafik tersebut. Puncak pertama terjadi di sekitar awal tahun 2025 (Januari - April) dan puncak kedua terjadi di awal tahun 2026 (Januari - April). Ini menandakan periode puncak musim hujan harian yang terakumulasi.
* Lembah Tren: Garis merah merosot tajam hingga di bawah rentang 100 mm di sekitar bulan Juli - September baik pada tahun 2025 maupun 2026, yang menandakan periode musim kemarau.

**Rolling Standard Deviation**
* Volatilitas Tinggi (Garis Hitam Naik): Pada akhir 2024 (sekitar bulan November ke Desember), garis hitam naik drastis menyentuh angka 250. Artinya, pada bulan-bulan tersebut terjadi perubahan curah hujan yang sangat ekstrem dari bulan sebelumnya (misal dari bulan yang sangat kering langsung melompat ke bulan yang sangat basah). Hal yang sama berulang di pertengahan tahun 2025 (Maret - Juli).
* Volatilitas Rendah (Garis Hitam Turun): Di sekitar bulan Agustus - September 2025, garis hitam ikut drop ke bawah (di bawah 50). Ini berarti variasi antar bulan di periode tersebut sangat kecil. Udara dan cuacanya stabil secara konsisten, yaitu sama-sama kering/jarang hujan di masa kemarau.

##Moving Average
"""

ma_3 = monthly_rr.rolling(window=3).mean()
ma_6 = monthly_rr.rolling(window=6).mean()

plt.figure(figsize=(9, 4))
plt.plot(monthly_rr, label='Data Asli (Monthly RR)', color='blue', alpha=0.3)
plt.plot(ma_3, label='3-Month Moving Average', color='orange', linewidth=2)
plt.plot(ma_6, label='6-Month Moving Average', color='red', linewidth=2)

plt.title('Analisis Pergerakan Tren dengan Moving Average')
plt.xlabel('Tanggal')
plt.ylabel('Curah Hujan (mm)')
plt.legend()
plt.grid(True)
plt.show()

"""**3-Month Moving Average**
* Garis ini masih mengikuti lekukan fluktuasi jangka pendek, tetapi berhasil memotong puncak-puncak tajam yang ekstrem (misalnya puncak biru di atas 600 mm pada awal 2025 diredam menjadi sekitar 400 mm saja).
* Garis oranye ini sangat bagus untuk melihat perubahan tren musiman yang lebih cepat, seperti transisi dari musim kemarau ke musim hujan yang berjarak beberapa bulan saja.

**6-Month Moving Average**
* Garis merah terlihat jauh lebih halus, landai, dan bergeser agak ke kanan (mengalami lag / keterlambatan) dibanding garis lainnya. Hal ini terjadi karena matematika rata-rata memerlukan data 6 bulan ke belakang sebelum bisa membentuk satu titik baru.
* Garis merah ini mengabaikan fluktuasi bulanan yang kecil dan fokus memperlihatkan tren makro (tren jangka panjang tahunan). Iklim di wilayah ini memiliki dua gelombang siklus tahunan yang sangat masif dan teratur.
"""

df['Tanggal'] = pd.to_datetime(df['Tanggal'])

monthly_rr = df.groupby(pd.Grouper(key='Tanggal', freq='MS'))['RR'].sum()

decomp = seasonal_decompose(monthly_rr, model='additive', period=12)
decomp.plot()
plt.show()

"""**Analisis Tren**
* Garis tren naik bertahap dari paruh kedua tahun 2024 hingga mencapai puncak tertingginya di pertengahan tahun 2025 (sekitar Juli/Agustus 2025), lalu menukik turun secara konsisten menuju pertengahan tahun 2026.
* Iklim pada periode tahun 2025 cenderung memiliki intensitas curah hujan akumulatif yang lebih basah atau tinggi dibandingkan periode tahun 2024 dan 2026. Tren ini membantu model mendeteksi pergeseran jangka panjang melampaui perubahan bulan ke bulan.

**Analisis Seasonal**
* Bentuk gelombang yang identik dan berulang persis antara siklus tahun pertama (2024–2025) dan tahun kedua (2025–2026). Nilainya berosilasi di sekitar angka 0 (karena menggunakan model additive).
* Wilayah data ini memiliki karakteristik musim hujan dan kemarau yang sangat teratur. Pola naik-turun yang tajam ini menunjukkan transisi ekstrem yang terprediksi dari bulan ke bulan di setiap tahunnya.

**Analisis Residual**
* Mayoritas titik berada tepat di garis nol, yang berarti model dekomposisi berhasil mengekstrak pola tren dan musim secara sempurna. Namun, ada dua titik ekstrem: satu titik anomali negatif di awal 2025 (curah hujan turun mendadak lebih rendah dari normalnya) dan satu titik anomali positif kuat di awal 2026 (terjadi lonjakan curah hujan yang jauh lebih tinggi dari pola musim hujan normal).

#Train-Test Split
"""

df['Tanggal'] = pd.to_datetime(df['Tanggal'], dayfirst=True, errors='coerce')
df = df[(df['Tanggal'] >= '2024-07-14') & (df['Tanggal'] <= '2026-07-13')].reset_index(drop=True)

df['RR'] = df['RR'].clip(lower=0)

for lag in [1, 3, 7]:
    df[f'RR_lag_{lag}'] = df['RR'].shift(lag)

df['bulan'] = df['Tanggal'].dt.month
df['hari'] = df['Tanggal'].dt.day

df = df.dropna().reset_index(drop=True)

X = df.drop(columns=['Tanggal', 'DDD_CAR', 'RR'], errors='ignore')
y = df['RR']

split_index = int(len(df) * 0.8)
X_train, X_test = X.iloc[:split_index], X.iloc[split_index:]
y_train, y_test = y.iloc[:split_index], y.iloc[split_index:]

"""#Scaling"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""#Training Model

##SVM
"""

model_svm = SVR(kernel='rbf', C=5.0, epsilon=0.1)
model_svm.fit(X_train_scaled, y_train)

y_pred_svm = model_svm.predict(X_test_scaled)
y_pred_svm = np.clip(y_pred_svm, a_min=0, a_max=None)

mae_svm = mean_absolute_error(y_test, y_pred_svm)
rmse_svm = np.sqrt(mean_squared_error(y_test, y_pred_svm))

plt.figure(figsize=(12, 5))
plt.plot(dates_test.values[:100], y_test.values[:100], label='Aktual', color='black', alpha=0.8)
plt.plot(dates_test.values[:100], y_pred_svm[:100], label='Prediksi SVM', color='blue', linestyle='--')
plt.legend()
plt.title("Prediksi Curah Hujan (RR) - SVM")
plt.xlabel("Tanggal")
plt.ylabel("Curah Hujan (mm)")
plt.gcf().autofmt_xdate()
plt.show()

"""##Random Forest"""

model_rf = RandomForestRegressor(n_estimators=200, max_depth=5, random_state=42, n_jobs=-1)
model_rf.fit(X_train_scaled, y_train)

y_pred_rf = model_rf.predict(X_test_scaled)
y_pred_rf = np.clip(y_pred_rf, a_min=0, a_max=None)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

dates_test = df['Tanggal'].iloc[split_index:]

plt.figure(figsize=(12, 5))
plt.plot(dates_test.values[:100], y_test.values[:100], label='Aktual', color='black', alpha=0.8)
plt.plot(dates_test.values[:100], y_pred_rf[:100], label='Prediksi Random Forest', color='teal', linestyle='--')
plt.legend()
plt.title("Prediksi Curah Hujan (RR) - Random Forest")
plt.xlabel("Tanggal")
plt.ylabel("Curah Hujan (mm)")
plt.gcf().autofmt_xdate()
plt.show()

"""##XGBoost Regression"""

model_xgb = XGBRegressor(n_estimators=200, max_depth=5, learning_rate=0.05, random_state=42)
model_xgb.fit(X_train_scaled, y_train)

y_pred_xgb = model_xgb.predict(X_test_scaled)
y_pred_xgb = np.clip(y_pred_xgb, a_min=0, a_max=None)

mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

dates_test = df['Tanggal'].iloc[split_index:]

plt.figure(figsize=(12, 5))
plt.plot(dates_test.values[:100], y_test.values[:100], label='Aktual', color='black', alpha=0.8)
plt.plot(dates_test.values[:100], y_pred_xgb[:100], label='Prediksi XGBoost', color='green', linestyle='--')
plt.legend()
plt.title("Prediksi Curah Hujan (RR) - XGBoost")
plt.xlabel("Tanggal")
plt.ylabel("Curah Hujan (mm)")
plt.gcf().autofmt_xdate() # Merapikan posisi tanggal miring
plt.show()

"""##Light GBM"""

model_lgb = LGBMRegressor(n_estimators=200, max_depth=5, learning_rate=0.05, random_seed=42, verbose=-1)
model_lgb.fit(X_train_scaled, y_train)

y_pred_lgb = model_lgb.predict(X_test_scaled)
y_pred_lgb = np.clip(y_pred_lgb, a_min=0, a_max=None)

mae_lgb = mean_absolute_error(y_test, y_pred_lgb)
rmse_lgb = np.sqrt(mean_squared_error(y_test, y_pred_lgb))

dates_test = df['Tanggal'].iloc[split_index:]

plt.figure(figsize=(12, 5))
plt.plot(dates_test.values[:100], y_test.values[:100], label='Aktual', color='black', alpha=0.8)
plt.plot(dates_test.values[:100], y_pred_lgb[:100], label='Prediksi LightGBM', color='darkorange', linestyle='--')
plt.legend()
plt.title("Prediksi Curah Hujan (RR) - LightGBM")
plt.xlabel("Tanggal")
plt.ylabel("Curah Hujan (mm)")
plt.gcf().autofmt_xdate()
plt.show()

"""##LSTM"""

X_train_3d = np.reshape(X_train_scaled, (X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_3d = np.reshape(X_test_scaled, (X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

model_lstm = Sequential([
    LSTM(64, activation='relu', input_shape=(X_train_3d.shape[1], X_train_3d.shape[2]), return_sequences=False),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1)
])
model_lstm.compile(optimizer='adam', loss='mse')
model_lstm.fit(X_train_3d, y_train, epochs=50, batch_size=16, verbose=0)

y_pred_lstm = model_lstm.predict(X_test_3d).flatten()
y_pred_lstm = np.clip(y_pred_lstm, a_min=0, a_max=None)

mae_lstm = mean_absolute_error(y_test, y_pred_lstm)
rmse_lstm = np.sqrt(mean_squared_error(y_test, y_pred_lstm))

dates_test = df['Tanggal'].iloc[split_index:]

plt.figure(figsize=(12, 5))
plt.plot(dates_test.values[:100], y_test.values[:100], label='Aktual', color='black', alpha=0.8)
plt.plot(dates_test.values[:100], y_pred_lstm[:100], label='Prediksi LSTM', color='red', linestyle='--')
plt.legend()
plt.title("Prediksi Curah Hujan (RR) - LSTM")
plt.xlabel("Tanggal")
plt.ylabel("Curah Hujan (mm)")
plt.gcf().autofmt_xdate()
plt.show()

"""#Model Evaluation"""

def calculate_mape(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    mask = y_true > 0
    if not np.any(mask):
        return np.nan
    return np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100

# Pastikan semua variabel prediksi Anda sudah siap
models_preds = {
    'XGBoost': y_pred_xgb,
    'SVM': y_pred_svm,
    'LSTM': y_pred_lstm,
    'Random Forest': y_pred_rf,
    'LightGBM': y_pred_lgb
}

mae_results = []
rmse_results = []
mape_results = []

for name, pred in models_preds.items():
    mae = mean_absolute_error(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    mape = calculate_mape(y_test, pred)

    mae_results.append(mae)
    rmse_results.append(rmse)
    mape_results.append(mape)

df_evaluasi_akhir = pd.DataFrame({
    'MAE (mm)': mae_results,
    'RMSE (mm)': rmse_results,
    'MAPE (%)': mape_results
}, index=models_preds.keys())

display(df_evaluasi_akhir.round(3))

"""Nilai MAPE di semua model sangat besar (bahkan di atas 100%) adalah hal yang sangat wajar dalam prediksi curah hujan harian. Pada hari-hari dengan hujan sangat rintik (misalnya aktual 1 mm) jika model memprediksi 3 mm (selisih hanya 2 mm), nilai MAPEnya langsung melonjak menjadi 200%.

**SVM**
* SVM memiliki MAE terendah (6.137 mm) dan MAPE paling kecil (91.803%)
* Nilai RMSE-nya sedikit lebih tinggi (14.430 mm), yang berarti sesekali SVM bisa kecolongan membuat tebakan yang meleset cukup jauh saat cuaca ekstrem tiba-tiba berubah.

**LSTM**
* LSTM memiliki RMSE terendah (12.857 mm). Karena formula RMSE memberikan penalti besar pada eror yang besar, nilai yang rendah ini membuktikan bahwa LSTM sangat bagus dalam meredam kesalahan prediksi yang fatal.
* MAE-nya sedikit di bawah SVM dan MAPEnya cukup tinggi (162.595%).

#Forecasting - LSTM
"""

forecast_periods = [7, 14, 30]
max_forecast = max(forecast_periods)

last_row = X_test.iloc[-1:].copy()

future_predictions = []
current_row = last_row.copy()

last_date = pd.to_datetime(df['Tanggal'].iloc[-1])
current_date = last_date

fitur_kolom = ['TN', 'TX', 'TAVG', 'RH_AVG', 'SS', 'FF_X', 'DDD_X', 'FF_AVG',
               'RR_lag_1', 'RR_lag_3', 'RR_lag_7', 'bulan', 'hari']

prediction_history = list(df['RR'].iloc[-10:].values)

for i in range(max_forecast):
    current_date = current_date + pd.Timedelta(days=1)
    current_row['RR_lag_1'] = prediction_history[-1]
    current_row['RR_lag_3'] = prediction_history[-3]
    current_row['RR_lag_7'] = prediction_history[-7]

    current_row['bulan'] = current_date.month
    current_row['hari'] = current_date.day

    features_to_scale = current_row[fitur_kolom]
    features_scaled = scaler.transform(features_to_scale)
    features_3d = np.reshape(features_scaled, (1, 1, features_scaled.shape[1]))

    pred_val = model_lstm.predict(features_3d, verbose=0).flatten()[0]
    pred_val = max(0.0, float(pred_val))

    future_predictions.append(pred_val)
    prediction_history.append(pred_val)

future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=max_forecast, freq='D')

plt.figure(figsize=(14, 6))

dates_actual_plot = df['Tanggal'].iloc[-30:]
y_actual_plot = df['RR'].iloc[-30:]

plt.plot(dates_actual_plot, y_actual_plot, label='Data Aktual (30 Hari Terakhir)', color='black', linewidth=2)

colors = {7: 'green', 14: 'blue', 30: 'red'}
styles = {7: '-', 14: '--', 30: '-.'}

for days in forecast_periods:
    plt.plot(
        future_dates[:days],
        future_predictions[:days],
        label=f'Forecast {days} Hari ke Depan',
        color=colors[days],
        linestyle=styles[days],
        marker='o',
        markersize=4
    )

plt.title("Visualisasi Future Forecasting Curah Hujan (RR) Menggunakan Model LSTM")
plt.xlabel("Tanggal")
plt.ylabel("Curah Hujan (mm)")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.gcf().autofmt_xdate()
plt.show()

"""#Download Model"""

model_lstm.save('model_lstm.keras')

model_lstm.save('model_lstm.h5')

import joblib

joblib.dump(scaler, 'scaler.pkl')

