# -*- coding: utf-8 -*-
"""Scraping_Youtube_Pelemahan Rupiah

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L941UKfzNYZSA3AiZNMB4H2kYmLNpDu8

#Install Library
"""

pip install youtube-comment-downloader

"""#Import Library"""

import pandas as pd
from youtube_comment_downloader import YoutubeCommentDownloader
pd.set_option('display.max_colwidth', None)

"""#Youtube"""

from numpy import common_type
downloader = YoutubeCommentDownloader()
url = "https://www.youtube.com/watch?v=2FPx1_CUzYQ"
comments = []
for comment in downloader.get_comments_from_url(url):
    comments.append(comment)
df_youtube = pd.DataFrame(comments)

df_youtube

df_youtube = df_youtube[['text']].copy()

df_youtube.to_excel("pelemahan rupiah.xlsx", index=False)